### PR TITLE
Tah Dah

### PR DESCRIPTION
**Pull request by isavegas**
I made shit work. Fuck you, @TheWhoAreYouPerson.

### CODE REVIEW

**Comment by TheWhoAreYouPerson** [comment]
* GenericContainer:
	* fixed it in the repository, so its all good now, that is irrelevant
* SpecificUtilities:
	* block texture names need to be called in the blocks, fix it (Its being set in GenericContainer anyway, they don't need to be anywhere unless override
	* Fluid Milk is fine. Remind me to put more detail into the fluid later.
* Block*:
	* wtf is up wioth your indenting on thge call for super in BlockDatabase
	* Unlocalized names are set in GenericContainer
	* Can you explain onBlockActivate in BlockPotionRemover a bit better?
* FluidMilk:
	* Remind me to add some shit to it later (texture, attributes, etc) (eg //TODO )
* TileDatabase:
	* whats wrong with the equality check? it seems fine :c

**Comment by isavegas** [comment]
The block super was automated. :p
The TileDatabase check was crashing me. I decided that I would rewrite one later, and removed it entirely.

**Comment by isavegas** [comment]
The block super was automated. :p
The TileDatabase check was crashing me. I decided that I would rewrite one later, and removed it entirely.

**Comment by TheWhoAreYouPerson** [comment]
I merged the pull request manually while fiing some of our derps cased by my git noobyness. Closed.

**Comment by isavegas** [comment]
You did? ;D Well, I'd better rebase my fork to your main branch.

**Pull request closed without merging**
